#' Gamma dispersion (`shape`) for the basic delay-distribution UI
#'
#' @description
#' Maps the basic delay "variability" radio choices in [delays_input()] to the
#' shape parameter of a Gamma distribution (`shape` in [stats::rgamma()]). With
#' the mean held fixed (`scale = mean / shape`), `shape` controls the skewness
#' of the tail (skewness = 2 / sqrt(shape)): `"low"` (`shape = 20`) is
#' near-symmetric, `"moderate"` (`shape = 5`) is a classic right skew, and
#' `"high"` (`shape = 2`) has a long, heavy tail.
#'
#' @keywords internal
BASIC_DELAY_SHAPE <- c(
  low = 20,
  moderate = 5,
  high = 2
)

#' Generate [bslib::accordion()] with inputs for parameterising the
#' `incubation_period` or `onset_to_isolation` argument in
#' [ringbp::delay_opts()]
#'
#' @param ns A namespace created with [shiny::NS()].
#' @param delay_type A `character` string, either `"incubation"` or
#' `"onset_to_isolation"`, selecting which delay distribution to parameterise.
#' Controls the input IDs, labels and tooltips generated by this function.
#' @param id_prefix A `character` string prepended to every input ID generated
#' by this function (e.g. `"dct_"`). Allows the inputs to be reused several
#' times within the same module (e.g. one set per contact tracing strategy)
#' without clashing. Defaults to `""` (no prefix).
#' @param ... [dots] Not used, will throw a warning if arguments are supplied.
#'
#' @return A [bslib::accordion()] object.
#' @keywords internal
delays_input <- function(ns,
                         delay_type = c("incubation", "onset_to_isolation"),
                         id_prefix = "",
                         ...) {
  chkDots(...)
  delay_type <- match.arg(delay_type)

  # Delay-type-specific display text (IDs are always delay_type-based, never
  # derived from these strings).
  delay <- switch(
    delay_type,
    incubation = list(
      name = "incubation period",
      Name = "Incubation period",
      tip = "The incubation period is the time between infection and symptom
      onset.",
      mean_tip = "The average number of days between infection and symptom
      onset."
    ),
    onset_to_isolation = list(
      name = "onset-to-isolation delay",
      Name = "Onset-to-isolation delay",
      tip = "The onset-to-isolation delay is the time between symptom onset and
      being isolated.",
      mean_tip = "The average number of days between symptom onset and being
      isolated."
    )
  )

  # Advanced Lognormal defaults: incubation defaults are per-pathogen (under
  # disease_x), onset-to-isolation defaults are top-level in PROPOSE_DEFAULTS.
  defaults <- switch(
    delay_type,
    incubation = list(
      meanlog = PROPOSE_DEFAULTS$disease_x$incubation_meanlog,
      sdlog = PROPOSE_DEFAULTS$disease_x$incubation_sdlog
    ),
    onset_to_isolation = list(
      meanlog = PROPOSE_DEFAULTS$onset_to_isolation_meanlog,
      sdlog = PROPOSE_DEFAULTS$onset_to_isolation_sdlog
    )
  )
  # default basic mean derived from the advanced (lnorm) defaults, rounded to
  # 1 dp for a simpler default value
  basic_mean_default <- round(
    epiparameter::convert_params_to_summary_stats(
      "lnorm",
      meanlog = defaults$meanlog,
      sdlog = defaults$sdlog
    )$mean,
    1
  )

  # Helper to build prefixed, namespaced input IDs
  iid <- function(suffix) ns(paste0(id_prefix, suffix))
  # conditionalPanel conditions referencing the prefixed, delay-typed inputs
  ui_is <- function(mode) {
    sprintf("input.%s%s_ui == '%s'", id_prefix, delay_type, mode)
  }
  dist_is <- function(value) {
    sprintf(
      "input.%s%s_distribution == '%s'", id_prefix, delay_type, value
    )
  }

  accordion(
    accordion_panel(
      title = delay$Name,
      icon = bs_icon("hourglass-split"),

      # basic or advanced UI options
      radioButtons(
        inputId = iid(paste0(delay_type, "_ui")),
        label = "User mode",
        choices = list(
          "Basic" = "basic",
          "Advanced" = "advanced"
        )
      ),

      # basic delay UI
      conditionalPanel(
        condition = ui_is("basic"),
        numericInput(
          iid(paste0("basic_", delay_type, "_mean")),
          label = tagList(
            paste0("Average ", delay$name, " (days)"),
            tooltip(bs_icon("info-circle"), delay$mean_tip)
          ),
          value = basic_mean_default,
          min = 0
        ),
        radioButtons(
          inputId = iid(paste0("basic_", delay_type, "_variability")),
          label = tagList(
            paste(delay$Name, "variability"),
            tooltip(
              bs_icon("info-circle"),
              sprintf(
                "How much the %s varies between individuals. Higher variability
                gives a longer tail, where some cases take much longer than the
                average. These options set the shape of a Gamma distribution
                with the average above: low (near-symmetric), moderate, and
                high (long-tailed).",
                delay$name
              )
            )
          ),
          choices = list(
            "Low variability" = "low",
            "Moderate variability" = "moderate",
            "High variability" = "high"
          ),
          selected = "moderate"
        ),
        ns = ns
      ),

      # advanced delay UI
      conditionalPanel(
        condition = ui_is("advanced"),
        selectInput(
          inputId = iid(paste0(delay_type, "_distribution")),
          label = tagList(
            paste(delay$Name, "distribution"),
            tooltip(
              bs_icon("info-circle"),
              paste(
                delay$tip,
                "Select the parametric distribution used to model this delay.
                Lognormal, Gamma, and Weibull are all right-skewed distributions
                commonly used to model this delay."
              )
            )
          ),
          choices = list(
            "Lognormal" = "lnorm",
            "Gamma" = "gamma",
            "Weibull" = "weibull"
          )
        ),
        conditionalPanel(
          condition = dist_is("lnorm"),
          numericInput(
            iid(paste0(delay_type, "_meanlog")),
            label = tagList(
              paste(delay$Name, "meanlog"),
              tooltip(
                bs_icon("info-circle"),
                sprintf(
                  "The mean of the %s on the natural-log scale (a parameter of
                  the Lognormal distribution). Note that the mean of the %s
                  itself is exp(meanlog + sdlog^2 / 2), not exp(meanlog).",
                  delay$name, delay$name
                )
              )
            ),
            value = defaults$meanlog
          ),
          numericInput(
            iid(paste0(delay_type, "_sdlog")),
            label = tagList(
              paste(delay$Name, "sdlog"),
              tooltip(
                bs_icon("info-circle"),
                sprintf(
                  "The standard deviation of the %s on the natural-log scale
                  (a parameter of the Lognormal distribution). Larger values
                  produce a more dispersed distribution with a heavier right
                  tail.",
                  delay$name
                )
              )
            ),
            value = defaults$sdlog
          ),
          ns = ns
        ),
        conditionalPanel(
          condition = dist_is("gamma"),
          numericInput(
            iid(paste0(delay_type, "_shape")),
            label = tagList(
              paste(delay$Name, "shape"),
              tooltip(
                bs_icon("info-circle"),
                shape_tip("Gamma", delay$name)
              )
            ),
            value = 2
          ),
          numericInput(
            iid(paste0(delay_type, "_scale")),
            label = tagList(
              paste(delay$Name, "scale"),
              tooltip(
                bs_icon("info-circle"),
                scale_tip("Gamma", delay$name)
              )
            ),
            value = 1
          ),
          ns = ns
        ),
        conditionalPanel(
          condition = dist_is("weibull"),
          numericInput(
            iid(paste0(delay_type, "_shape")),
            label = tagList(
              paste(delay$Name, "shape"),
              tooltip(
                bs_icon("info-circle"),
                shape_tip("Weibull", delay$name)
              )
            ),
            value = 2
          ),
          numericInput(
            iid(paste0(delay_type, "_scale")),
            label = tagList(
              paste(delay$Name, "scale"),
              tooltip(
                bs_icon("info-circle"),
                scale_tip("Weibull", delay$name)
              )
            ),
            value = 1
          ),
          ns = ns
        ),
        ns = ns
      )
    ),
    open = FALSE
  )
}
