#' Negative Binomial dispersion (`k`) for the basic pathogen transmissibility
#' UI
#'
#' @description
#' Maps the `basic_transmission_variability` radio choices in
#' [offspring_input()] to the Negative Binomial dispersion parameter (`size`
#' in [stats::rnbinom()]). `"homogeneous"` (`k = Inf`) is equivalent to a
#' Poisson offspring distribution, `"moderate"` (`k = 1`) to a Geometric,
#' and `"high"` (`k = 0.1`) gives strong superspreading.
#'
#' @keywords internal
BASIC_K <- c(
  homogeneous = Inf,
  moderate = 1,
  high = 0.1
)

# tooltip messages for offspring distribution parameters
offspring_tip <- HTML(
  "The probability distribution governing the number of
              secondary cases produced by each infected individual. Negative
              Binomial allows for heterogeneity in transmission (superspreading)
              via the dispersion parameter <em>k</em>; Poisson assumes
              homogeneous transmission; Geometric has more heterogeneity in
              transmission than Poisson, and is a special case of the Negative
              Binomial with <em>k</em> = 1."
)

disp_tip <- HTML(
  "The dispersion parameter (<em>k</em>) of the Negative Binomial offspring
    distribution. Lower values indicate greater heterogeneity in
    transmission (i.e. more superspreading), while <em>k</em> = 1 is
    equivalent to the Geometric and large values of <em>k</em>
  approximate a Poisson distribution."
)

#' Generate [bslib::accordion()] with inputs for parameterising `community` and
#' `isolated` arguments in [ringbp::offspring_opts()]
#'
#' @param ns A namespace created with [shiny::NS()].
#' @param ... [dots] Not used, will throw a warning if arguments are supplied.
#'
#' @return A [bslib::accordion()] object.
#' @keywords internal
offspring_input <- function(ns, ...) {
  chkDots(...)

  r0_tip <- function(setting) {
    paste0(
      "The basic reproduction number for transmission among ", setting,
      " cases. Represents the average number of secondary cases generated by a
      single infectious individual in a fully susceptible population."
    )
  }

  accordion(
    accordion_panel(
      title = "Pathogen transmissibility",
      icon = bs_icon("diagram-3-fill"),

      # basic or advanced UI options
      radioButtons(
        inputId = ns("transmissibility_ui"),
        label = "User mode",
        choices = list(
          "Basic" = "basic",
          "Advanced" = "advanced"
        )
      ),

      # basic transmissibility UI
      conditionalPanel(
        condition = "input.transmissibility_ui == 'basic'",
        numericInput(
          ns("basic_community_r0"),
          label = tagList(
            "Average number of secondary infections (R0)",
            tooltip(
              bs_icon("info-circle"),
              "The basic reproduction number (R0) is the average number of
              secondary infections caused by a primary infection in a population
              of entirely susceptible individuals."
            )
          ),
          value = 2
        ),
        numericInput(
          ns("basic_isolated_r0"),
          label = tagList(
            "Average number of secondary infections while isolated (R0)",
            tooltip(bs_icon("info-circle"), r0_tip("isolated"))
          ),
          value = PROPOSE_DEFAULTS$disease_x$isolated_r0
        ),
        radioButtons(
          inputId = ns("basic_transmission_variability"),
          label = tagList(
            "Transmission variability",
            tooltip(
              bs_icon("info-circle"),
              "How much the number of secondary infections varies between
              individuals. Homogeneous transmission means everyone infects a
              similar number of people, while higher variability allows for
              superspreading, where a few individuals cause most infections.
              These options set the dispersion (k) of a Negative Binomial
              offspring distribution: homogeneous (k = Inf, equivalent to
              Poisson), moderate (k = 1, equivalent to Geometric), and high
              (k = 0.1)."
            )
          ),
          choices = list(
            "Homogeneous transmission" = "homogeneous",
            "Moderate transmission variability" = "moderate",
            "High transmission variability" = "high"
          )
        ),
        ns = ns
      ),

      # advanced transmissibility UI
      conditionalPanel(
        condition = "input.transmissibility_ui == 'advanced'",
        selectInput(
          inputId = ns("community_offspring_distribution"),
          label = tagList(
            "Community Offspring Distribution",
            tooltip(bs_icon("info-circle"), offspring_tip)
          ),
          choices = list(
            "Negative Binomial" = "nbinom",
            "Poisson" = "pois",
            "Geometric" = "geom"
          )
        ),
        numericInput(
          ns("community_r0"),
          label = tagList(
            "Community R0",
            tooltip(bs_icon("info-circle"), r0_tip("community"))
          ),
          value = PROPOSE_DEFAULTS$disease_x$community_r0
        ),
        conditionalPanel(
          condition = "input.community_offspring_distribution == 'nbinom'",
          numericInput(
            ns("community_disp"),
            label = tagList(
              HTML("Community Dispersion (<em>k</em>)"),
              tooltip(bs_icon("info-circle"), disp_tip)
            ),
            value = PROPOSE_DEFAULTS$disease_x$community_disp
          ),
          ns = ns
        ),
        selectInput(
          inputId = ns("isolated_offspring_distribution"),
          label = tagList(
            "Isolated Offspring Distribution",
            tooltip(bs_icon("info-circle"), offspring_tip)
          ),
          choices = list(
            "Negative Binomial" = "nbinom",
            "Poisson" = "pois",
            "Geometric" = "geom"
          )
        ),
        numericInput(
          ns("isolated_r0"),
          label = tagList(
            "Isolated R0",
            tooltip(bs_icon("info-circle"), r0_tip("isolated"))
          ),
          value = PROPOSE_DEFAULTS$disease_x$isolated_r0
        ),
        conditionalPanel(
          condition = "input.isolated_offspring_distribution == 'nbinom'",
          numericInput(
            ns("isolated_disp"),
            label = tagList(
              HTML("Isolated Dispersion (<em>k</em>)"),
              tooltip(bs_icon("info-circle"), disp_tip)
            ),
            value = PROPOSE_DEFAULTS$disease_x$isolated_disp
          ),
          ns = ns
        ),
        ns = ns
      )
    ),
    open = FALSE
  )
}

#' Generate [bslib::accordion()] with a simple `From`/`To`/`By` sweep over the
#' community basic reproduction number (R0)
#'
#' @description
#' A prototype transmissibility input for sweeping community R0 over a [seq()].
#' Unlike [offspring_input()] this deliberately omits the basic/advanced user
#' mode toggle. It exposes a single community offspring distribution, dispersion
#' (`k`, for the Negative Binomial) and a single isolated R0 that are held fixed
#' across the sweep.
#'
#' @param ns A namespace created with [shiny::NS()].
#' @param from,to,by `numeric` R0 values seeding the `From`/`To`/`By` inputs
#'   that parameterise the [seq()] of community R0 values to sweep over.
#' @param ... [dots] Not used, will throw a warning if arguments are supplied.
#'
#' @return A [bslib::accordion()] object.
#' @keywords internal
r0_seq_input <- function(ns, from, to, by, ...) {
  chkDots(...)

  r0_seq_tip <- "The basic reproduction number (R0) for community transmission:
    the average number of secondary cases generated by a single infectious
    individual in a fully susceptible population. The 'From', 'To' and 'By'
    inputs parameterise a seq() of R0 values over which the outbreak simulation
    is repeated."

  accordion(
    accordion_panel(
      title = "Pathogen transmissibility (R0 sweep):",
      icon = bs_icon("diagram-3-fill"),
      selectInput(
        ns("community_offspring_distribution"),
        label = tagList(
          "Community offspring distribution",
          tooltip(bs_icon("info-circle"), offspring_tip)
        ),
        choices = list(
          "Negative Binomial" = "nbinom",
          "Poisson" = "pois",
          "Geometric" = "geom"
        )
      ),
      numericInput(
        ns("community_r0_from"),
        label = tagList(
          "Community R0 From", tooltip(bs_icon("info-circle"), r0_seq_tip)
        ),
        value = from,
        min = 0
      ),
      numericInput(
        ns("community_r0_to"),
        label = tagList(
          "Community R0 To", tooltip(bs_icon("info-circle"), r0_seq_tip)
        ),
        value = to,
        min = 0
      ),
      numericInput(
        ns("community_r0_by"),
        label = tagList(
          "Community R0 By", tooltip(bs_icon("info-circle"), r0_seq_tip)
        ),
        value = by,
        min = 0
      ),
      conditionalPanel(
        condition = "input.community_offspring_distribution == 'nbinom'",
        numericInput(
          ns("community_disp"),
          label = tagList(
            HTML("Community dispersion (<em>k</em>)"),
            tooltip(bs_icon("info-circle"), disp_tip)
          ),
          value = 0.5,
          min = 0
        ),
        ns = ns
      ),
      numericInput(
        ns("isolated_r0"),
        label = tagList(
          "Isolated R0",
          tooltip(
            bs_icon("info-circle"),
            "The basic reproduction number for transmission among isolated
            cases, held fixed across the R0 sweep."
          )
        ),
        value = 0,
        min = 0
      ),
      conditionalPanel(
        condition = "input.community_offspring_distribution == 'nbinom'",
        numericInput(
          ns("isolated_disp"),
          label = tagList(
            HTML("Isolated dispersion (<em>k</em>)"),
            tooltip(bs_icon("info-circle"), disp_tip)
          ),
          value = 0.5,
          min = 0
        ),
        ns = ns
      )
    ),
    open = TRUE
  )
}

#' Register input-validation feedback for [r0_seq_input()]
#'
#' Validates that `From`/`To`/`By` are non-negative (with `By > 0`) and that
#' `From <= To`.
#'
#' @param input The Shiny `input` reactive of the calling module.
#'
#' @return Invisible `NULL`; called for side-effects.
#' @keywords internal
r0_seq_feedback_server <- function(input) {
  observeEvent(input$community_r0_from, {
    req(!is.na(input$community_r0_from))
    if (input$community_r0_from < 0) {
      showFeedbackDanger(
        "community_r0_from",
        text = "Error: 'From' R0 cannot be negative."
      )
    } else {
      hideFeedback("community_r0_from")
    }
  })
  observeEvent(input$community_r0_to, {
    req(!is.na(input$community_r0_to))
    if (input$community_r0_to < 0) {
      showFeedbackDanger(
        "community_r0_to",
        text = "Error: 'To' R0 cannot be negative."
      )
    } else if (!is.na(input$community_r0_from) &&
               input$community_r0_to < input$community_r0_from) {
      showFeedbackDanger(
        "community_r0_to",
        text = "Error: 'To' must be greater than or equal to 'From'."
      )
    } else {
      hideFeedback("community_r0_to")
    }
  })
  observeEvent(input$community_r0_by, {
    req(!is.na(input$community_r0_by))
    if (input$community_r0_by <= 0) {
      showFeedbackDanger(
        "community_r0_by",
        text = "Error: 'By' must be greater than 0."
      )
    } else {
      hideFeedback("community_r0_by")
    }
  })
  invisible(NULL)
}

#' Register input-validation feedback for [offspring_input()]
#'
#' Companion server function intended to be called once inside a module
#' [shiny::moduleServer()] block. Wires up [shinyFeedback::showFeedbackDanger()]
#' for the advanced (`community_r0`, `isolated_r0`) and basic
#' (`basic_community_r0`, `basic_isolated_r0`) reproduction number inputs.
#'
#' @param input The Shiny `input` reactive of the calling module.
#'
#' @return Invisible `NULL`; called for side-effects.
#' @keywords internal
offspring_feedback_server <- function(input) {
  observeEvent(input$community_r0, {
    req(!is.na(input$community_r0))
    if (input$community_r0 < 0) {
      showFeedbackDanger(
        "community_r0",
        text = "Error: Community R0 cannot be negative."
      )
    } else {
      hideFeedback("community_r0")
    }
  })
  observeEvent(input$isolated_r0, {
    req(!is.na(input$isolated_r0))
    if (input$isolated_r0 < 0) {
      showFeedbackDanger(
        "isolated_r0",
        text = "Error: Isolated R0 cannot be negative."
      )
    } else {
      hideFeedback("isolated_r0")
    }
  })
  observeEvent(input$basic_community_r0, {
    req(!is.na(input$basic_community_r0))
    if (input$basic_community_r0 < 0) {
      showFeedbackDanger(
        "basic_community_r0",
        text = "Error: R0 cannot be negative."
      )
    } else {
      hideFeedback("basic_community_r0")
    }
  })
  observeEvent(input$basic_isolated_r0, {
    req(!is.na(input$basic_isolated_r0))
    if (input$basic_isolated_r0 < 0) {
      showFeedbackDanger(
        "basic_isolated_r0",
        text = "Error: R0 cannot be negative."
      )
    } else {
      hideFeedback("basic_isolated_r0")
    }
  })
  invisible(NULL)
}
