#' Generate [bslib::accordion()] with inputs for parameterising `community` and
#' `isolated` arguments in [ringbp::offspring_opts()]
#'
#' @param ns A namespace created with [shiny::NS()].
#' @param ... [dots] Not used, will throw a warning if arguments are supplied.
#'
#' @return A [bslib::accordion()] object.
#' @keywords internal
offspring_input <- function(ns, ...) {
  chkDots(...)

  # tooltip messages for offspring distribution parameters
  offspring_tip <- HTML(
    "The probability distribution governing the number of
              secondary cases produced by each infected individual. Negative
              Binomial allows for heterogeneity in transmission (superspreading)
              via the dispersion parameter <em>k</em>; Poisson assumes
              homogeneous transmission; Geometric has more heterogeneity in
              transmission than Poisson, and is a special case of the Negative
              Binomial with <em>k</em> = 1."
  )
  r0_tip <- function(setting) {
    paste0(
      "The basic reproduction number for transmission among ", setting,
      " cases. Represents the average number of secondary cases generated by a
      single infectious individual in a fully susceptible population."
    )
  }
  disp_tip <- HTML(
    "The dispersion parameter (<em>k</em>) of the Negative Binomial offspring
    distribution. Lower values indicate greater heterogeneity in
    transmission (i.e. more superspreading), while <em>k</em> = 1 is
    equivalent to the Geometric and large values of <em>k</em>
    approximate a Poisson distribution."
  )

  accordion(
    accordion_panel(
      title = "Offspring distribution parameters:",
      icon = bs_icon("diagram-3-fill"),
      selectInput(
        inputId = ns("community_offspring_distribution"),
        label = tagList(
          "Community Offspring Distribution",
          tooltip(bs_icon("info-circle"), offspring_tip)
        ),
        choices = list(
          "Negative Binomial" = "nbinom",
          "Poisson" = "pois",
          "Geometric" = "geom"
        )
      ),
      conditionalPanel(
        condition = "input.community_offspring_distribution == 'nbinom'",
        numericInput(
          ns("community_r0"),
          label = tagList(
            "Community R0",
            tooltip(bs_icon("info-circle"), r0_tip("community"))
          ),
          value = PROPOSE_DEFAULTS$disease_x$community_r0
        ),
        numericInput(
          ns("community_disp"),
          label = tagList(
            HTML("Community Dispersion (<em>k</em>)"),
            tooltip(bs_icon("info-circle"), disp_tip)
          ),
          value = PROPOSE_DEFAULTS$disease_x$community_disp
        ),
        ns = ns
      ),
      conditionalPanel(
        condition = "input.community_offspring_distribution == 'pois'",
        numericInput(
          ns("community_r0"),
          label = tagList(
            "Community R0",
            tooltip(bs_icon("info-circle"), r0_tip("community"))
          ),
          value = PROPOSE_DEFAULTS$disease_x$community_r0
        ),
        ns = ns
      ),
      conditionalPanel(
        condition = "input.community_offspring_distribution == 'geom'",
        numericInput(
          ns("community_r0"),
          label = tagList(
            "Community R0",
            tooltip(bs_icon("info-circle"), r0_tip("community"))
          ),
          value = PROPOSE_DEFAULTS$disease_x$community_r0
        ),
        ns = ns
      ),
      selectInput(
        inputId = ns("isolated_offspring_distribution"),
        label = tagList(
          "Isolated Offspring Distribution",
          tooltip(bs_icon("info-circle"), offspring_tip)
        ),
        choices = list(
          "Negative Binomial" = "nbinom",
          "Poisson" = "pois",
          "Geometric" = "geom"
        )
      ),
      conditionalPanel(
        condition = "input.isolated_offspring_distribution == 'nbinom'",
        numericInput(
          ns("isolated_r0"),
          label = tagList(
            "Isolated R0",
            tooltip(bs_icon("info-circle"), r0_tip("isolated"))
          ),
          value = PROPOSE_DEFAULTS$disease_x$isolated_r0
        ),
        numericInput(
          ns("isolated_disp"),
          label = tagList(
            HTML("Isolated Dispersion (<em>k</em>)"),
            tooltip(bs_icon("info-circle"), disp_tip)
          ),
          value = PROPOSE_DEFAULTS$disease_x$isolated_disp
        ),
        ns = ns
      ),
      conditionalPanel(
        condition = "input.isolated_offspring_distribution == 'pois'",
        numericInput(
          ns("isolated_r0"),
          label = tagList(
            "Isolated R0",
            tooltip(bs_icon("info-circle"), r0_tip("isolated"))
          ),
          value = PROPOSE_DEFAULTS$disease_x$isolated_r0
        ),
        ns = ns
      ),
      conditionalPanel(
        condition = "input.isolated_offspring_distribution == 'geom'",
        numericInput(
          ns("isolated_r0"),
          label = tagList(
            "Isolated R0",
            tooltip(bs_icon("info-circle"), r0_tip("isolated"))
          ),
          value = PROPOSE_DEFAULTS$disease_x$isolated_r0
        ),
        ns = ns
      )
    ),
    open = FALSE
  )
}
